AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Stage:
    Type: String
  Project:
    Type: String


Resources:
  ContentBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: BucketOwnerFullControl

  LogsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: BucketOwnerFullControl

  ContentBucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub /infra/${Stage}/${Project}/ContentBucket
      Value: !Ref ContentBucket

  LogsBucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub /infra/${Stage}/${Project}/LogsBucket
      Value: !Ref LogsBucket